name: Get Android SHA Keys

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get_sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get SHA Keys
        run: |
          # Ба папкаи android мегузарем
          cd android
          # Иҷозат медиҳем, ки файл кор кунад
          chmod +x gradlew
          # Фармонро иҷро мекунем
          ./gradlew signingReport | grep -E "Variant|SHA1|SHA-256"
