name: Get Android SHA Keys

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get_sha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Find and Get SHA Keys
        run: |
          # Ҷустуҷӯи файли gradlew дар тамоми папкаҳо
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          
          if [ -z "$GRADLEW_PATH" ]; then
            echo "Хато: Файли gradlew ёфт нашуд!"
            exit 1
          fi
          
          echo "Файл дар ин ҷо ёфт шуд: $GRADLEW_PATH"
          
          # Гузаштан ба папкаи файл ва иҷрои фармон
          cd $(dirname $GRADLEW_PATH)
          chmod +x gradlew
          ./gradlew signingReport | grep -E "Variant|SHA1|SHA-256"
