name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ] # агар номи веткаи асосиат master бошад, master навис

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        run: |
          git remote add hf https://github-actions:${{ secrets.GH_TOKEN }}@huggingface.co/spaces/Mahmadmurodov/TajikShop
          git push --force hf main
